{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "endpointPizzaCreationLatency_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revenue/minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizzas_total{pizzaMetric=\"revenue\"}[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "endpointLatency_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizzas sold/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(pizzas_total{pizzaMetric=\"sold\"}[1m]) * 60",
     "legendFormat": "pizzas sold"
    },
    {
     "expr": "rate(pizzas_total{pizzaMetric=\"creationFailures\"}[1m]) * 60",
     "legendFormat": "pizzas failed to sell"
    }
   ]
  },
  {
   "title": "System",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpuPercentage_total", "legendFormat": "CPU" },
    { "expr": "memoryPercentage_total", "legendFormat": "Memory" }
   ]
  },
  {
   "title": "Active Users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "activeUsers_total", "legendFormat": "activeUsers" }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "rate(methods_total[1m]) * 60", "legendFormat": "__auto" },
    {
     "expr": "sum(rate(methods_total[1m])) * 60",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Authentication attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(authAttemps_total{status=\"success\"}[1m]) * 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(authAttemps_total{status=\"failure\"}[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}